apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: pulseflow
resources:
  - config
  - api.yaml
  - worker.yaml
labels:
  - pairs:
      app.kubernetes.io/part-of: pulseflow
    includeSelectors: true
