apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: pulseflow
resources:
  - ../../base/config
  - ../../base/migration
images:
  - name: pulseflow
    newName: bom.ocir.io/bm7wpbkcaaqu/pulseflow
    newTag: 0.1.0
