apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: pulseflow
resources:
  - postgres.yaml
  - redis.yaml
  - kafka.yaml
  - kafka-topics-job.yaml
labels:
  - pairs:
      app.kubernetes.io/part-of: pulseflow
      app.kubernetes.io/environment: oracle-free
    includeSelectors: true
